### ISSUE TITLE
Snapshots with VM memory

### ISSUE THREAD

**Issue by timogoebel** [ATIX-AG/foreman_snapshot_management#17]
Currently, all snapshots are created including the VM memory. This is very slow for large VMs. It should be considered if this can be deactivated by default or if an option can be provided.

https://github.com/ATIX-AG/foreman_snapshot_management/blob/ca7b9636c291003b32aea68fa1366226fa431573/app/models/foreman_snapshot_management/vmware_extensions.rb#L12

Needs to be extended with `:memory => false` (defaults to true).

**Comment by mdellweg** [comment]
@timogoebel would you mind, to take a look at 
https://github.com/ATIX-AG/foreman_snapshot_management/commit/be3e87252374091bddc884bbf43334cde642bad9 ?
I have no idea how to verify that this works. There is no (read only) `memory` attribute on the snapshot object of the fog library.
