### ISSUE TITLE
Vcenter ports

### ISSUE THREAD

**Issue by gaddcasey2** [ATIX-AG/foreman_snapshot_management#37]
What ports are used from the foreman server to the vCenter? can we get these listed in the documentation?

**Comment by timogoebel** [comment]
Just https access to the vcenter from Foreman should suffice. The plugin does not need any additional ports.

**Comment by mdellweg** [comment]
I can confirm that. As the plugin is using the same fog vsphere bindings as the supporting foreman, it should be able to talk to the vCenter, whenever the compute_resource can.
