### ISSUE TITLE
Snapshot Actions should be auditable

### ISSUE THREAD

**Issue by Klaas-** [ATIX-AG/foreman_snapshot_management#7]
Create/remove/rollback of a snapshot should be present in foreman audit log

**Comment by mdellweg** [comment]
Sadly, the audit functionality used by foreman is depending on ActiveRecords and cannot (easily?) be used by plain ActiveModels.

**Comment by timogoebel** [comment]
@mdellweg: Why don't you use the host model so store the audit data?

```
h = Host.find(1)
h.audit_comment = 'Reverted to snapshot 1234.'
h.save
```

**Comment by mdellweg** [comment]
@timogoebel I will take that as a suggestion. Thank you!
As far as it is a question: I have not thought about that.
