### ISSUE TITLE
connection to vsphere

### ISSUE THREAD

**Issue by toni-do** [ATIX-AG/foreman_snapshot_management#96]
This plugin is exactly what I was looking for. Unfortunately, I don't understand how this plugin works. Some more background/documentation would be nice.

1. does this Plugin work without PowerCLI?
2. where must the URL and the credentials to the vCenter get defined?

**Comment by maximiliankolb** [comment]
Hi @toni-do 

1. I have not heard of PowerCLI before but I'll ask.
2. You reuse the credentials as defined for your compute resource. See [Adding a VMware Connection to Foreman server](https://docs.theforeman.org/nightly/Provisioning_Hosts/index-katello.html#Adding_a_VMware_Connection_to_Server_vmware-provisioning).

For more information, see [Installing the Snapshot Management Plug-in](https://docs.theforeman.org/nightly/Managing_Hosts/index-katello.html#Installing_the_Snapshot_Management_Plugin_managing-hosts) and [Creating Snapshots of a Managed Host](https://docs.theforeman.org/nightly/Managing_Hosts/index-katello.html#Creating_Snapshots_of_a_Managed_Host_managing-hosts) on docs.theforeman.org.

**Comment by toni-do** [comment]
Thanks for your quick response. That explains a lot. 

The user defined in the "Compute Resource" is the one which needs the rights Snapshot Viewer, Viewer, Snapshot Manger and Site Manager?
